version: "4.13"
   
services:
  postgres_odoo_16_local:
    image: postgres:13.4
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoopass
      - POSTGRES_PORT=5432
    ports:
      - "8022:5432"
    expose:
      - "8022"  
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres_dump:/backups

  odoo_v16_pgadmin:
    container_name: odoo_v16_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8021:80"


  odoo_v16:
    build:
      context: .
      dockerfile: compose_config/Dockerfile
    image: odoo_v16
    command: python3 /opt/odoo/odoo-16/odoo-bin -c /etc/odoo/odoo-server.conf
    volumes:
      - type: bind
        source: ./external_addons/
        target: /opt/odoo/external_addons
    ports:
      - "8020:8069"
    depends_on:
      - postgres_odoo_16_local
 